/*

  shadow.H

  Author: <your name>
  Last Updated: 2007-07-06

  This framework is generated by EasySYS 0.3.0
  This template file is copying from QuickSYS 0.3.0 written by Chunhua Liu
  
 //=============================================
  Modify by PLK_XiaoWei[0GiNr]
  http://www.0GiNr.com
  //=============================================
*/

#include <devioctl.h>

#ifndef _SHADOW_H
#define _SHADOW_H 1
//============================================
#define DEVICE_NAME L"\\Device\\devshadow" //Driver Name
#define LINK_NAME L"\\DosDevices\\shadow"  //Link Name
//============================================
#define IOCTL_BASE	0x800

#define MY_CTL_CODE(i) \
	CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_BASE+i, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_HELLO	MY_CTL_CODE(1)
//============================================

#endif
